### ISSUE TITLE
How to connect to other containers when network is in service:openvpn

### ISSUE THREAD

**Issue by kensongoo** [kuthz/docker-openvpn-killswitch#1]
Hi There,

     First of all OpenVPN kill switch works great. I have a question regarding how to refer to other container services once we set the network_mode to service:openvpn. It seems like other containers, like redis, is not reachable anymore. Below is my test docker compose file.

```
version: '3.3'

services:
  app: 
    build:
      context: .
    environment:
      NODE_ENV: development
      TZ: UTC
      DEBUG: "*:*"
      POSTGRES_URL: postgresql://user:password@db:5432/test
      REDIS_URL: redis://redis:6379
    depends_on:
      - openvpn
      - db
      - redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
  redis:
    image: redis
    ports:
      - "6379:6379"
  openvpn:
    image: kuthz/openvpn-killswitch
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - type: bind
        source: ./openvpn-config
        target: /etc/openvpn/profile/
```

**Comment by kuthz** [comment]
Hi @kensongoo 

thx for the feedback, you can refer to this example. https://github.com/kuthz/btstack/blob/master/docker-compose.yml

Since the network is handled by the openvpn service, you need to expose the port on the openvpn service.
